# Use an official Python runtime as a base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the local directory contents into the container
COPY . /app

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install GitPython

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World
ENV GIT_PYTHON_REFRESH=silent
ENV GIT_PYTHON_GIT_EXECUTABLE=/usr/bin/git
ENV REPO_URL=https://github.com/YourRepo/Example

# Run process_repository.py when the container launches
# CMD ["python", "script_repo_process.py", "${REPO_URL}"]
CMD ["python", "script_repo_process.py"]
